version: "3.8"

services:
  app:
    container_name: akarsu-dys
    image: ctekkaya/akarsu-dys:0.1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
